version: "3.9"
services:
  trigger:
    build:
      context: ./trigger
    container_name: trigger
    networks:
      - app-network
    depends_on:
      - app2
      - app1  # เพิ่ม app1
    ports:
      - "5000:5000"  # เปิดพอร์ตสำหรับทดสอบ  
    restart: always
  
  app1:
    build:
      context: ./app1
    container_name: app1
    networks:
      - app-network
    ports:
      - "5002:5001"  # พอร์ตภายนอก 5002 เชื่อมกับพอร์ตภายใน 5001
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  app2:
    build:
      context: ./app2
    container_name: app2
    networks:
      - app-network
    ports:
      - "5001:5001"  # พอร์ตภายนอก 5001 เชื่อมกับพอร์ตภายใน 5001
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
