apiVersion: v1
kind: Service
metadata:
  name: trigger-service
spec:
  selector:
    app: trigger
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger
  template:
    metadata:
      labels:
        app: trigger
    spec:
      containers:
      - name: trigger
        image: trigger:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

