# Service: เปิดการเชื่อมต่อระหว่างภายนอกหรือภายในคลัสเตอร์กับแอป
apiVersion: v1
kind: Service
metadata:
  name: app1-service  # ชื่อ Service
spec:
  selector:
    app: app1         # เชื่อมโยงกับ Pod ที่มี label app=app1
  ports:
    - protocol: TCP
      port: 5001      # พอร์ตที่ Service เปิด
      targetPort: 5001  # พอร์ตที่ Pod ใช้งาน
  type: ClusterIP     # Service นี้สามารถเข้าถึงได้ภายในคลัสเตอร์เท่านั้น

---
# Deployment: กำหนดวิธีการสร้าง Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1          # ชื่อ Deployment
spec:
  replicas: 1         # จำนวน Pod
  selector:
    matchLabels:
      app: app1       # เลือก Pod ที่มี label app=app1
  template:
    metadata:
      labels:
        app: app1     # กำหนด label ให้ Pod
    spec:
      containers:
      - name: app1    # ชื่อคอนเทนเนอร์
        image: app1:1.0.1  # ชื่อ Image ที่จะใช้
        imagePullPolicy: IfNotPresent  # ดึง Image ใหม่หากไม่มีใน Local
        ports:
        - containerPort: 5001  # พอร์ตภายใน Container
